### ISSUE TITLE
Would you accept xunit (other) unit tests for Serialization and Compression pull?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nxrighthere/NetStack#1]
in `Tests` folder with `csproj` referencing files from `Source`?

**Comment by nxrighthere** [comment]
I'm using BenchmarkDotNet for such tests locally I just didn't push it into the repository. Feel free to pull your tests but please, drop everything into `Benchmarks` folder instead of `Tests`. 👌

**Comment by nxrighthere** [comment]
By the way, a fork with more performant serialization/compression made by my friend is available [here](https://github.com/Vincenz099/NetworkingHelpers) if you are interested.

**Comment by dzmitry-lahoda** [comment]
@nxrighthere , would you mind to describe why you do not push benchmarks int repository?

**Comment by nxrighthere** [comment]
I see the point to include it when you can compare it with some alternatives like general-purpose serializers for example. In my case I'm using synthetic benchmarking for basic smoke tests internally. On top of this, it's more code to maintain.

**Comment by Vincenz099** [comment]
By all means create a serialization benchmark project, that tests difirent serializers with certain data sets and compare their serialization and de-serialization performance and resulting byte sizes. That would be an interesting project!

**Comment by dzmitry-lahoda** [comment]
@Vincenz099 , I run tests on you `BitBuffer`, and it gives larger bytes output. Here I run @nxrighthere  `BitBuffer` with expected values for yours. And it gives systematically less bytes. I see less sense in faster serializer of it does not compress so well. Also it is cool to have better API (but more reusable seems to move Half and Quaternion into BitBufferExtensions).

```
using System;
using Xunit;

namespace NetStack.Serialization
{
    public class BitBufferTests
    {
        [Fact]
        public void BoolIsBit7()
        {
            var buffer = new BitBuffer();
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            //buffer.Finish();
            Assert.Equal(1, buffer.Length);
        }

        [Fact]
        public void BoolIsBit9()
        {
            var buffer = new BitBuffer();
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);
            buffer.AddBool(true);

            buffer.AddBool(true);
            Assert.Equal(2, buffer.Length);
        }

        [Fact]
        public void ByteMax3()
        {
            var buffer = new BitBuffer();
            buffer.AddByte(byte.MaxValue);
            buffer.AddByte(byte.MaxValue);
            buffer.AddByte(byte.MaxValue);
            Assert.Equal(4, buffer.Length);
        }

        [Fact]
        public void ByteMin3()
        {
            var buffer = new BitBuffer();
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);
            Assert.Equal(4, buffer.Length);
        }     

        [Fact]
        public void ByteMin8()
        {
            var buffer = new BitBuffer();
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);
            buffer.AddByte(byte.MinValue);                        
            Assert.Equal(9, buffer.Length);
        }         

        [Fact]
        public void ByteHalf()
        {
            var buffer = new BitBuffer();
            buffer.AddByte(byte.MaxValue/2);
            buffer.AddByte(byte.MaxValue/2);
            buffer.AddByte(byte.MaxValue/2);
            buffer.AddByte(byte.MaxValue/2);
            buffer.AddByte(byte.MaxValue/2);
            buffer.AddByte(byte.MaxValue/2);
            buffer.AddByte(byte.MaxValue/2);
            buffer.AddByte(byte.MaxValue/2);             
            //buffer.Finish();         
            Assert.Equal(9, buffer.Length);
        }   


        [Fact]
        public void ByteShortMin4()
        {
            var buffer = new BitBuffer();
            buffer.AddShort(short.MinValue);
            buffer.AddShort(short.MinValue);
            buffer.AddShort(short.MinValue);
            buffer.AddShort(short.MinValue);    
            //buffer.Finish();                  
            Assert.Equal(8, buffer.Length);
        }                     

        [Fact]
        public void UIntMax()
        {
            var buffer = new BitBuffer();
            buffer.AddUInt(uint.MaxValue);
            Assert.Equal(6, buffer.Length);
        }

        [Fact]
        public void UIntMin()
        {
            var buffer = new BitBuffer();
            buffer.AddUInt(uint.MinValue);
            Assert.Equal(2, buffer.Length);
        }

        [Fact]
        public void BoolReadWrite()
        {
            var buffer = new BitBuffer();
            buffer.AddBool(true);
            //buffer.Finish();
            // buffer.ResetReadPos();
            // Assert.True(buffer.ReadBool());
        }
    }
}
```

```
Starting test execution, please wait...
Starting test execution, please wait...
[xUnit.net 00:00:00.99]     NetStack.Serialization.BitBufferTests.ByteHalf [FAIL]
[xUnit.net 00:00:01.00]     NetStack.Serialization.BitBufferTests.ByteMin3 [FAIL]
[xUnit.net 00:00:01.00]     NetStack.Serialization.BitBufferTests.UIntMax [FAIL]
[xUnit.net 00:00:01.00]     NetStack.Serialization.BitBufferTests.ByteMax3 [FAIL]
[xUnit.net 00:00:01.00]     NetStack.Serialization.BitBufferTests.ByteMin8 [FAIL]
[xUnit.net 00:00:01.00]     NetStack.Serialization.BitBufferTests.ByteShortMin4 [FAIL]
[xUnit.net 00:00:01.00]     NetStack.Serialization.BitBufferTests.UIntMin [FAIL]

Total tests: 3. Passed: 3. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.0231 Seconds
Failed   NetStack.Serialization.BitBufferTests.ByteHalf
Error Message:
 Assert.Equal() Failure
Expected: 9
Actual:   8
Stack Trace:
   at NetStack.Serialization.BitBufferTests.ByteHalf() in F:\src\games\NetStack\Tests\NetStack.Serialization.Tests\BitBufferTests.cs:line 88
Failed   NetStack.Serialization.BitBufferTests.ByteMin3
Error Message:
 Assert.Equal() Failure
Expected: 4
Actual:   3
Stack Trace:
   at NetStack.Serialization.BitBufferTests.ByteMin3() in F:\src\games\NetStack\Tests\NetStack.Serialization.Tests\BitBufferTests.cs:line 57
Failed   NetStack.Serialization.BitBufferTests.UIntMax
Error Message:
 Assert.Equal() Failure
Expected: 6
Actual:   5
Stack Trace:
   at NetStack.Serialization.BitBufferTests.UIntMax() in F:\src\games\NetStack\Tests\NetStack.Serialization.Tests\BitBufferTests.cs:line 109
Failed   NetStack.Serialization.BitBufferTests.ByteMax3
Error Message:
 Assert.Equal() Failure
Expected: 4
Actual:   3
Stack Trace:
   at NetStack.Serialization.BitBufferTests.ByteMax3() in F:\src\games\NetStack\Tests\NetStack.Serialization.Tests\BitBufferTests.cs:line 47
Failed   NetStack.Serialization.BitBufferTests.ByteMin8
Error Message:
 Assert.Equal() Failure
Expected: 9
Actual:   8
Stack Trace:
   at NetStack.Serialization.BitBufferTests.ByteMin8() in F:\src\games\NetStack\Tests\NetStack.Serialization.Tests\BitBufferTests.cs:line 72
Failed   NetStack.Serialization.BitBufferTests.ByteShortMin4
Error Message:
 Assert.Equal() Failure
Expected: 8
Actual:   12
Stack Trace:
   at NetStack.Serialization.BitBufferTests.ByteShortMin4() in F:\src\games\NetStack\Tests\NetStack.Serialization.Tests\BitBufferTests.cs:line 101
Failed   NetStack.Serialization.BitBufferTests.UIntMin
Error Message:
 Assert.Equal() Failure
Expected: 2
Actual:   1
Stack Trace:
   at NetStack.Serialization.BitBufferTests.UIntMin() in F:\src\games\NetStack\Tests\NetStack.Serialization.Tests\BitBufferTests.cs:line 117

Total tests: 10. Passed: 3. Failed: 7. Skipped: 0.
Test Run Failed.
Test execution time: 2.0569 Seconds

```

**Comment by Vincenz099** [comment]
I'll check what's up. :)

**Comment by Vincenz099** [comment]
@dzmitry-lahoda can you check master now after this commit: 
https://github.com/Vincenz099/NetworkingHelpers/commit/002e5fe556457f04d7d421d335fc40805a687f3a

**Comment by dzmitry-lahoda** [comment]
that helped, thanks

**Comment by Vincenz099** [comment]
@dzmitry-lahoda intrested to see some benchmark/test project of various serializers. 💯

**Comment by dzmitry-lahoda** [comment]
I doubt I will run benchmark soon. I guess will run as soon as next read https://github.com/dzmitry-lahoda/ObjectLayoutInspector/blob/feature/unsafelayout/src/ObjectLayoutInspector/UnsafeLayout.cs and combined.

**Comment by dzmitry-lahoda** [comment]
```
               Method |       Mean |     Error |     StdDev |
--------------------- |-----------:|----------:|-----------:|
 BitBuffer0b0000_0000 |   342.0 ns |  3.890 ns |   3.639 ns |
    BitOps0b0000_0000 |   340.4 ns |  3.436 ns |   3.214 ns |
 BitBuffer0b1111_1111 | 3,689.3 ns | 47.723 ns |  42.305 ns |
    BitOps0b1111_1111 | 2,628.2 ns | 17.803 ns |  16.653 ns |
 BitBuffer0b0000_1111 | 3,711.1 ns | 71.488 ns | 100.216 ns |
    BitOps0b0000_1111 | 2,638.8 ns | 17.487 ns |  16.358 ns |
```

**Comment by dzmitry-lahoda** [comment]
```
               Method |       Mean |     Error |   StdDev |
--------------------- |-----------:|----------:|---------:|
 BitBuffer0b0000_0000 |   350.5 ns |  8.104 ns | 10.25 ns |
    BitOps0b0000_0000 |   364.5 ns |  7.298 ns | 17.20 ns |
 BitBuffer0b1111_1111 | 3,664.7 ns | 33.041 ns | 30.91 ns |
    BitOps0b1111_1111 | 2,688.1 ns | 53.506 ns | 61.62 ns |
 BitBuffer0b0000_1111 | 3,159.3 ns | 35.466 ns | 33.17 ns |
    BitOps0b0000_1111 | 2,785.5 ns | 53.988 ns | 70.20 ns |
```

I doubt i will write zeroes often, also i like .NET Standard 2.1 (Unity will support it) and our server is x86.

**Comment by nxrighthere** [comment]
@dzmitry-lahoda Try to inline `FindHighestBitPosition()` method.

**Comment by Vincenz099** [comment]
I don't know why this is an important thing to measure, The bitbuffer is meant to serialize data for networking purposes. by all means I can try to improve FromArray/ToArray  FromSpan/ToSpan but I think the real gains are in serializing/deserializing a lot of data and how much that data is taking in the bitbuffer.

**Comment by dzmitry-lahoda** [comment]
it was inlined. i want to depend on .net standard 2.0(future 2.1) on all methods as possible, and incidentally methods from standard are faster. So table approach is interesting.

**Comment by dzmitry-lahoda** [comment]
No sure so. I BDN Log2 from `BoundedRange` and `BitOps` (I undrestand that test only 64 bits x86, but I see BitOps balance 32 vs 64 bit optimization, and as .NET Core officially ARM, so I guess ARM too).
``
     Method |      Mean |     Error |    StdDev |
----------- |----------:|----------:|----------:|
 BitOpsLog2 |  6.407 ns | 0.1387 ns | 0.1298 ns |
     BoundedRangeLog2| 11.376 ns | 0.2326 ns | 0.2176 ns |
```

**Comment by Vincenz099** [comment]
Try same LogTable as before with this:
public static int Log2(uint number) {
            if (number <= 0xffffu) {
                if (number > 0xffu) {
                    return 8 + LogTable256[number >> 8];
                }
                return LogTable256[number];
            }
            if (number <= 0xffffffu) {
                return 16 + LogTable256[number >> 16];
            }
            return 24 + LogTable256[number >> 24];
        }

I suppose BitOps works less good in mono by the way.

**Comment by dzmitry-lahoda** [comment]
As game writes many many bools I have improved it twice https://github.com/dzmitry-lahoda/NetStack/commit/46522d4d457d82dcb2d7bcbc984937aa15abc769 . 
I guess will do something like that for up to 4 bytes numbers (use not true or false for skip, but skip next X number like in Unity FPS)

**Comment by dzmitry-lahoda** [comment]
Also I think of next
```
byte[] x = ReadNetwork();
ref byte b = ref x[header];
ref uint s = ref Unsafe.As<byte, uint>(ref b);
bitbuffer.AddFoo(ref s, someFoo);
```

I hope that design will be of exact performance on Unity and .NET Core. Also I hope I can wrap patter into old API to retain legacy bitbuffer so people who cannot do zero go still can use without lost of perf. So idea is zero copy.

**Comment by Vincenz099** [comment]
Sadly Ref local vars are not supported in older unity :(
